### ISSUE TITLE
Issue14-Favorite button for images to save to local storage

### ISSUE THREAD

**Issue by jburz** [clarissareeve/Emotional_Media_Generator#19]

**Comment by jburz** [comment]
Kilee - add icon button to webpage
Jake - link button to save url to local storage

**Comment by jburz** [comment]
The local storage functionality is working.  We need the final buttons to link the click listener.

**Comment by jburz** [comment]
Buttons have been linked to click listener.

**Comment by kileelucero** [comment]
Created favorite icon (Transparent and Filled). Also added styling to every card with images/gifs loading.
