### ISSUE TITLE
Issue15-Favorite button for gifs to save to local storage

### ISSUE THREAD

**Issue by jburz** [clarissareeve/Emotional_Media_Generator#20]

**Comment by jburz** [comment]
The local storage functionality is working.  We need the final buttons to link the click listener.

**Comment by jburz** [comment]
I added the functionality for buttons to swap from transparent to solid on click in the gif, photos and random section and vice versa on the favorites section.

**Comment by jburz** [comment]
I also built functionality in to be able to remove images/gifs from favorites by clicking the heart button in favorites.

**Comment by kileelucero** [comment]
Created favorites icon (Transparent and filled) for each image/gif. Added Card styles to every image and gif loading.
