### ISSUE TITLE
issue 19 Get photographer credit for pexels

### ISSUE THREAD

**Issue by seanmena** [clarissareeve/Emotional_Media_Generator#28]
Get photographer credit for pexels

**Comment by jburz** [comment]
Guidelines
Whenever you are doing an API request make sure to show a prominent link to Pexels. You can use a text link (e.g. "Photos provided by Pexels") or a link with our logo.

Always credit our photographers when possible (e.g. "Photo by John Doe on Pexels" with a link to the photo page on Pexels).
